services:
- docker
script:
- docker build -t dok3r/vexriscv-build:$DOCKER_TAG .
- docker login -u="$DOCKER_HUB_LOGIN" -p="$DOCKER_HUB_PASSWORD"
- docker tag dok3r/vexriscv-build:$DOCKER_TAG dok3r/vexriscv:$DOCKER_TAG
- docker push dok3r/vexriscv:$DOCKER_TAG
